config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root "homes#top"

    get   "users",                    to: "users#index",  as: :users
    get   "users/:account_name",      to: "users#show",   as: :user
    get   "users/:account_name/edit", to: "users#edit",   as: :edit_user
    patch "users/:account_name",      to: "users#update", as: :update_user

    resources :artworks, only: %i[index show edit update destroy]
    resources :comments, only: %i[index destroy]
    resources :reports,  only: %i[index show update] do
      member do
        post :update_status
      end
    end
  end

  # 一般ユーザー
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root "homes#top"

    get     "users/:account_name",                to: "users#show",                 as: :user_profile
    get     "users/:account_name/edit",           to: "users#edit",                 as: :edit_user_profile
    patch   "users/:account_name",                to: "users#update",               as: :update_user_profile
    get     "users/:account_name/artworks",       to: "users#artworks",             as: :user_artworks
    get     "users/:account_name/liked_artworks", to: "users#liked_artworks",       as: :user_liked_artworks
    get     "users/:account_name/my_artworks",    to: "users#my_artworks",          as: :user_my_artworks
    post    "users/:account_name/relationships",  to: "relationships#create",       as: :user_follow
    delete  "users/:account_name/relationships",  to: "relationships#destroy",      as: :user_unfollow
    get     "users/:account_name/followings",     to: "relationships#followings",   as: :user_followings
    get     "users/:account_name/followers",      to: "relationships#followers",    as: :user_followers
    get     "confirm_deactivation",               to: "users#confirm_deactivation", as: :confirm_deactivation
    patch   "deactivate",                         to: "users#deactivate",           as: :deactivate

    resources :artworks do
      member do
        get   :editor
        patch :update_canvas
      end
      collection do
        post :initialize_editor,  defaults: { format: "js" }
      end

      resource  :likes,     only: %i[create destroy], defaults: { format: "js" }
      resources :comments,  only: %i[create destroy], defaults: { format: "js" }
    end

    resources :reports, only: :create do
      collection do
        post :make, defaults: { format: "js" }
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
   MAX_CONTENT_LENGTH = 120

  belongs_to :user
  belongs_to :artwork

  has_many :reports, as: :reportable, dependent: :destroy

  # Commentレコードを取得する際、デフォルトで新しいコメントが先頭に来るようにする。
  default_scope { order(created_at: :desc) }

  scope :with_user_profile_images, -> { includes(user: { profile_image_attachment: :blob }) }
  scope :with_artwork_images, -> { includes(:artwork => { image_attachment: :blob }) }

  validates :content, presence: true, length: { maximum: MAX_CONTENT_LENGTH }

  def self.max_content_length
    MAX_CONTENT_LENGTH
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  # `RedirectHandler` モジュールのインクルード
  # このモジュールはリダイレクトに関する共通のメソッドを提供します。
  # 特定のアクション実行後、元のページに戻るための処理をサポートします。
  include RedirectHandler

  before_action :set_comment, only: %i[destroy]
  before_action :store_return_to, only: [:destroy]

  def index
    @comments = Comment.page(params[:page])
      .with_user_profile_images
      .with_artwork_images
  end

  def destroy
    @comment.destroy

    default_path = admin_comments_path
    notice = t("messages.admin.comment.destroy_success")

    redirect_to determine_redirect_path(default_path), notice: notice
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_details.html.erb
<div class="overflow-auto grow">
  <%
    user = comment.user
    artwork = comment.artwork
  %>
  <%= component "shared/table/base" do %>
    <%= component "shared/table/body" do %>

      <%= component(
        "shared/details_row",
        heading: t("activerecord.attributes.comment.content")
      ) do %>
        <div class="whitespace-normal max-w-[32rem]">
          <%= comment.content %>
        </div>
      <% end %>

      <%= component(
        "shared/details_row",
        heading: t("activerecord.attributes.comment.title")
      ) do %>
        <%= link_to artwork.title, admin_artwork_path(artwork), class: "font-bold text-blue-500 hover:underline" %>
      <% end %>

      <%= component(
        "shared/details_row",
        heading: t("activerecord.attributes.user.display_name")
      ) do %>
        <%= link_to user.display_name, admin_user_path(user.account_name), class: "font-bold text-blue-500 hover:underline" %>
      <% end %>
    <% end %>
  <% end %>

  <div class="mt-10 flex justify-evenly">
    <%= component(
      "shared/button",
      style: :outline,
      color: :red,
      path: admin_comment_path(comment, return_to: request.referer),
      method: :delete,
      data: {
        confirm: "Are you sure?"
      },
      class: "w-32"
    ) do %>
      <%= component "utils/icon_text", fa_class: "fa-solid fa-trash-can" do %>
        <%= t("comment.delete") %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/comments/_table.html.erb
<div class="overflow-auto">
  <%= component "shared/table/base" do %>
    <%= component "shared/table/header", headers: [
      "#",
      t("activerecord.attributes.artwork.image"),
      t("activerecord.attributes.artwork.title"),
      t("activerecord.attributes.user.display_name"),
      t("activerecord.attributes.comment.content"),
      ""
    ].compact %>
    <%= component "shared/table/body" do %>
      <%= render partial: "admin/comments/table_row", collection: comments, as: :comment %>
    <% end %>
  <% end %>
</div>
<%= paginate comments %>

app/views/admin/comments/_table_row.html.erb
<%
  user = comment.user
  artwork = comment.artwork
%>
<%= component "shared/table/row" do %>
  <%= component "shared/table/cell", is_header: true do %>
    <%= comment.id %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= component "artwork/image", artwork: artwork, size: :xxs %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= link_to artwork.title, admin_artwork_path(artwork), class: "font-bold text-blue-500 hover:underline" %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= link_to user.display_name, admin_user_path(user.account_name), class: "font-bold text-blue-500 hover:underline" %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <div class="truncate max-w-[24rem]">
      <%= comment.content %>
    </div>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= component(
      "shared/button",
      style: :outline,
      color: :red,
      path: admin_comment_path(comment, return_to: request.path),
      method: :delete,
      "data-confirm" => "Are you sure?",
      class: "w-8 h-8 mx-auto my-0"
    ) do %>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  <% end %>
<% end %>

app/views/admin/comments/index.html.erb
<%= component "shared/card", class: "my-10" do %>
  <h2 class="ml-6"><%= t("comment.list") %></h2>
  <%= render "admin/comments/table", comments: @comments %>
<% end %>