config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root "homes#top"

    get   "users",                    to: "users#index",  as: :users
    get   "users/:account_name",      to: "users#show",   as: :user
    get   "users/:account_name/edit", to: "users#edit",   as: :edit_user
    patch "users/:account_name",      to: "users#update", as: :update_user

    resources :artworks, only: %i[index show edit update destroy]
    resources :comments, only: %i[index destroy]
    resources :reports,  only: %i[index show update] do
      member do
        post :update_status
      end
    end
  end

  # 一般ユーザー
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root "homes#top"

    get     "users/:account_name",                to: "users#show",                 as: :user_profile
    get     "users/:account_name/edit",           to: "users#edit",                 as: :edit_user_profile
    patch   "users/:account_name",                to: "users#update",               as: :update_user_profile
    get     "users/:account_name/artworks",       to: "users#artworks",             as: :user_artworks
    get     "users/:account_name/liked_artworks", to: "users#liked_artworks",       as: :user_liked_artworks
    get     "users/:account_name/my_artworks",    to: "users#my_artworks",          as: :user_my_artworks
    post    "users/:account_name/relationships",  to: "relationships#create",       as: :user_follow
    delete  "users/:account_name/relationships",  to: "relationships#destroy",      as: :user_unfollow
    get     "users/:account_name/followings",     to: "relationships#followings",   as: :user_followings
    get     "users/:account_name/followers",      to: "relationships#followers",    as: :user_followers
    get     "confirm_deactivation",               to: "users#confirm_deactivation", as: :confirm_deactivation
    patch   "deactivate",                         to: "users#deactivate",           as: :deactivate

    resources :artworks do
      member do
        get   :editor
        patch :update_canvas
      end
      collection do
        post :initialize_editor,  defaults: { format: "js" }
      end

      resource  :likes,     only: %i[create destroy], defaults: { format: "js" }
      resources :comments,  only: %i[create destroy], defaults: { format: "js" }
    end

    resources :reports, only: :create do
      collection do
        post :make, defaults: { format: "js" }
      end
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @unread_reports = Report.where(is_read: false)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="my-10 mx-16 grid justify-items-center grid-cols-1 gap-y-16">
  <% if @unread_reports.size > 0 %>
    <%= component "shared/card", class: "w-full" do %>
      <div class="px-8 py-5 flex justify-center items-center font-bold bg-sky-200">
        <%= component "utils/icon_text", fa_class: "fa-solid fa-flag" do %>
          <%= t("messages.report.unread_notice", count: @unread_reports.size) %>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <%= component "shared/card", class: "w-96" do %>
    <%= link_to admin_users_path, class: "p-12 w-full h-full block space-y-5 text-center no-underline transition-colors text-emerald-950 bg-emerald-100 hover:bg-emerald-200" do %>
      <div class="text-5xl"><i class="fa-solid fa-users"></i></div>
      <div class="text-2xl font-bold tracking-wide"><%= t("user.list") %></div>
    <% end %>
  <% end %>
  <%= component "shared/card", class: "w-96" do %>
    <%= link_to admin_artworks_path, class: "p-12 w-full h-full block space-y-5 text-center no-underline transition-colors text-indigo-950 bg-indigo-100 hover:bg-indigo-200" do %>
      <div class="text-5xl"><i class="fa-solid fa-palette"></i></div>
      <div class="text-2xl font-bold tracking-wide"><%= t("artwork.list") %></div>
    <% end %>
  <% end %>
  <%= component "shared/card", class: "w-96" do %>
    <%= link_to admin_comments_path, class: "p-12 w-full h-full block space-y-5 text-center no-underline transition-colors text-amber-950 bg-amber-100 hover:bg-amber-200" do %>
      <div class="text-5xl"><i class="fa-solid fa-comments"></i></div>
      <div class="text-2xl font-bold tracking-wide"><%= t("comment.list") %></div>
    <% end %>
  <% end %>
</div>