config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root "homes#top"

    get   "users",                    to: "users#index",  as: :users
    get   "users/:account_name",      to: "users#show",   as: :user
    get   "users/:account_name/edit", to: "users#edit",   as: :edit_user
    patch "users/:account_name",      to: "users#update", as: :update_user

    resources :artworks, only: %i[index show edit update destroy]
    resources :comments, only: %i[index destroy]
    resources :reports,  only: %i[index show update] do
      member do
        post :update_status
      end
    end
  end

  # 一般ユーザー
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root "homes#top"

    get     "users/:account_name",                to: "users#show",                 as: :user_profile
    get     "users/:account_name/edit",           to: "users#edit",                 as: :edit_user_profile
    patch   "users/:account_name",                to: "users#update",               as: :update_user_profile
    get     "users/:account_name/artworks",       to: "users#artworks",             as: :user_artworks
    get     "users/:account_name/liked_artworks", to: "users#liked_artworks",       as: :user_liked_artworks
    get     "users/:account_name/my_artworks",    to: "users#my_artworks",          as: :user_my_artworks
    post    "users/:account_name/relationships",  to: "relationships#create",       as: :user_follow
    delete  "users/:account_name/relationships",  to: "relationships#destroy",      as: :user_unfollow
    get     "users/:account_name/followings",     to: "relationships#followings",   as: :user_followings
    get     "users/:account_name/followers",      to: "relationships#followers",    as: :user_followers
    get     "confirm_deactivation",               to: "users#confirm_deactivation", as: :confirm_deactivation
    patch   "deactivate",                         to: "users#deactivate",           as: :deactivate

    resources :artworks do
      member do
        get   :editor
        patch :update_canvas
      end
      collection do
        post :initialize_editor,  defaults: { format: "js" }
      end

      resource  :likes,     only: %i[create destroy], defaults: { format: "js" }
      resources :comments,  only: %i[create destroy], defaults: { format: "js" }
    end

    resources :reports, only: :create do
      collection do
        post :make, defaults: { format: "js" }
      end
    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
  MAX_DESCRIPTION_LENGTH = 200

  belongs_to :reportable, polymorphic: true
  belongs_to :reported_by_user, class_name: "User"

  enum reason: {
    malicious_expression: 0,
    inappropriate_content: 1,
    misinformation: 2,
    commercial_purposes: 3,
    spam: 4,
    other: 5
  }
  enum status: { pending: 0, processing: 1, resolved: 2 }

  validates :description, length: { maximum: MAX_DESCRIPTION_LENGTH }

  # Reportレコードを取得する際、デフォルトで新しい作品が先頭に来るようにする。
  default_scope { order(created_at: :desc) }
  scope :with_details, -> { includes(:reported_by_user, :reportable) }

  def self.max_description_length
    MAX_DESCRIPTION_LENGTH
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update update_status]

  def index
    @reports = Report.with_details.page(params[:page])
  end

  def show
    @report.update(is_read: true)
  end

  def edit
  end

  def update
    if @report.update(report_params)
    else
    end
  end

  def update_status
    if @report.update(status: params[:status])
      respond_to do |format|
        format.js
      end
    else

    end
  end

  private
  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:status)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
  def report_status_options
    Report.statuses.map do |key, _value|
      [t("enums.report.status.#{key}"), key]
    end
  end
end

app/views/admin/reports/_details.html.erb
<div class="overflow-auto p-6">
  <%
    reported_user = report.reported_by_user
  %>
  <%= component "shared/table/base" do %>
    <%= component "shared/table/body" do %>
      <%= component(
        "shared/details_row",
        heading: t("models.report.reported_by_user_id")
      ) do %>
        <%= link_to reported_user.display_name, admin_user_path(reported_user.account_name), class: "font-bold text-blue-500 hover:underline" %>
      <% end %>

      <%= component(
        "shared/details_row",
        heading: t("models.report.reportable_type")
      ) do %>
        <%= t("report.target.#{report.reportable_type.downcase}") %>
      <% end %>

      <%= component(
        "shared/details_row",
        heading: t("models.report.reason")
      ) do %>
        <%= report.reason_i18n %>
      <% end %>

      <%= component(
        "shared/details_row",
        heading: t("models.report.description")
      ) do %>
        <div class="whitespace-normal max-w-[32rem]">
          <%= report.description %>
        </div>
      <% end %>

      <%= component(
        "shared/details_row",
        heading: t("models.report.status")
      ) do %>
        <div id="status-label">
          <%= component "report/status_label", report: report, type: :selecting %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/admin/reports/_list.html.erb
<%= component "shared/card", class: "my-10" do %>
  <h2 class="ml-6"><%= t("report.list") %></h2>
  <div class="overflow-auto">
    <%= component "shared/table/base" do %>
      <%= component "shared/table/header", headers: [
        "#",
        "",
        t("models.report.reported_by_user_id"),
        t("models.report.reportable_type"),
        t("models.report.reason"),
        t("models.report.description"),
        t("models.report.status"),
      ].compact %>
      <%= component "shared/table/body" do %>
        <% reports.each do |report| %>
          <%
            reported_user = report.reported_by_user
          %>
          <%= component "shared/table/row" do %>
            <%= component "shared/table/cell", is_header: true do %>
              <%= report.id %>
            <% end %>
            <%= component "shared/table/cell" do %>
              <%= component "report/read_label", is_read: report.is_read %>
            <% end %>
            <%= component "shared/table/cell" do %>
              <%= link_to reported_user.display_name, admin_user_path(reported_user.account_name), class: "font-bold text-blue-500 hover:underline" %>
            <% end %>
            <%= component "shared/table/cell" do %>
              <%= link_to t("report.target.#{report.reportable_type.downcase}"), admin_report_path(report.id), class: "font-bold text-blue-500 hover:underline" %>
            <% end %>
            <%= component "shared/table/cell" do %>
              <%= report.reason_i18n %>
            <% end %>
            <%= component "shared/table/cell" do %>
              <div class="truncate max-w-[24rem]">
                <%= report.description %>
              </div>
            <% end %>
            <%= component "shared/table/cell" do %>
              <%= component "report/status_label", report: report %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <%= paginate reports %>
<% end %>

app/views/admin/reports/index.html.erb
<%= render "admin/reports/list", reports: @reports %>

app/views/admin/reports/show.html.erb
<%= component "shared/card", class: "my-10" do %>
  <h2 class="ml-6"><%= t("report.details") %></h2>
  <%= render "admin/reports/details", report: @report %>
  <h2 class="ml-6"><%= t("report.target_details.reported_#{@report.reportable_type.downcase}_details") %></h2>
  <div class="p-6">
    <% case @report.reportable_type %>
    <% when "User" %>
      <%= render "admin/users/details", user: @report.reportable %>
    <% when "Artwork" %>
      <%= render "admin/artworks/details", artwork: @report.reportable, author: @report.reportable.user %>
    <% when "Comment" %>
      <%= render "admin/comments/details", comment: @report.reportable %>
    <% end %>
    <div class="mt-4 pt-4 border-t border-gray-300 space-y-1">
      <div>
        <%= component "shared/back_link", path: admin_reports_path, text: t("report.list") %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/reports/update_status.js.erb
{
  const statusLabel = document.getElementById("status-label");
  statusLabel.innerHTML = `<%=
    j(component "report/status_label", report: @report, type: :selecting)
  %>`;
}