config/routes.rb
Rails.application.routes.draw do
  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root "homes#top"

    get   "users",                    to: "users#index",  as: :users
    get   "users/:account_name",      to: "users#show",   as: :user
    get   "users/:account_name/edit", to: "users#edit",   as: :edit_user
    patch "users/:account_name",      to: "users#update", as: :update_user

    resources :artworks, only: %i[index show edit update destroy]
    resources :comments, only: %i[index destroy]
    resources :reports,  only: %i[index show update] do
      member do
        post :update_status
      end
    end
  end

  # 一般ユーザー
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root "homes#top"

    get     "users/:account_name",                to: "users#show",                 as: :user_profile
    get     "users/:account_name/edit",           to: "users#edit",                 as: :edit_user_profile
    patch   "users/:account_name",                to: "users#update",               as: :update_user_profile
    get     "users/:account_name/artworks",       to: "users#artworks",             as: :user_artworks
    get     "users/:account_name/liked_artworks", to: "users#liked_artworks",       as: :user_liked_artworks
    get     "users/:account_name/my_artworks",    to: "users#my_artworks",          as: :user_my_artworks
    post    "users/:account_name/relationships",  to: "relationships#create",       as: :user_follow
    delete  "users/:account_name/relationships",  to: "relationships#destroy",      as: :user_unfollow
    get     "users/:account_name/followings",     to: "relationships#followings",   as: :user_followings
    get     "users/:account_name/followers",      to: "relationships#followers",    as: :user_followers
    get     "confirm_deactivation",               to: "users#confirm_deactivation", as: :confirm_deactivation
    patch   "deactivate",                         to: "users#deactivate",           as: :deactivate

    resources :artworks do
      member do
        get   :editor
        patch :update_canvas
      end
      collection do
        post :initialize_editor,  defaults: { format: "js" }
      end

      resource  :likes,     only: %i[create destroy], defaults: { format: "js" }
      resources :comments,  only: %i[create destroy], defaults: { format: "js" }
    end

    resources :reports, only: :create do
      collection do
        post :make, defaults: { format: "js" }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  MAX_DISPLAY_NAME_LENGTH = 24
  MAX_ACCOUNT_NAME_LENGTH = 24
  MAX_INTRODUCTION_LENGTH = 240

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum status: {
    active: 0,
    deactivated: 1,
    suspended: 2
  }

  # 保存先のサービスをここで指定する。
  if Rails.env.production?
    # 本番環境ではS3に保存する。
    has_one_attached :profile_image, service: :amazon_profile_images
  else
    # 開発環境ではローカルに保存する。
    has_one_attached :profile_image, service: :local
  end

  has_many :artworks,       dependent: :destroy
  has_many :likes,          dependent: :destroy
  has_many :comments,       dependent: :destroy
  has_many :liked_artworks, through:   :likes,     source: :artwork
  has_many :reports,        as:        :reportable, dependent: :destroy

  has_many :active_relationships,  class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings,            through: :active_relationships,  source: :followed
  has_many :followers,             through: :passive_relationships, source: :follower

  validates :display_name, presence: true, length: { maximum: MAX_DISPLAY_NAME_LENGTH }
  validates(
    :account_name,
    presence: true,
    uniqueness: {
      case_sensitive: false
    },
    format: {
      with: /\A[\w]+\z/,
      message: :invalid
    },
    length: {
      maximum: MAX_ACCOUNT_NAME_LENGTH
    }
  )
  validates :introduction, length: { maximum: MAX_INTRODUCTION_LENGTH }

  # Userレコードを取得する際、デフォルトで新しい作品が先頭に来るようにする。
  default_scope { order(created_at: :desc) }
  scope :with_details, -> { includes(:followings, :followers, profile_image_attachment: :blob) }
  # Userの検索
  scope :search, -> (query, status) {
    users = all
    users = users.where("display_name LIKE ? OR introduction LIKE ?", "%#{query}%", "%#{query}%") if query.present?
    users = users.where(status: status) if status.present?
    users
  }

  def active_for_authentication?
    super && (status == "active")
  end

  def get_profile_image
    if profile_image.attached?
      if Rails.env.production?
        "https://d39xcen2r68k3d.cloudfront.net/profile/#{profile_image.key}.webp"
      else
        profile_image
      end
    else
      nil
    end
  end

  def follow(user)
    active_relationships.create(followed_id: user.id) unless following?(user)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id)&.destroy
  end

  def following?(user)
    active_relationships.exists?(followed_id: user.id)
  end

  def self.max_display_name_length
    MAX_DISPLAY_NAME_LENGTH
  end

  def self.max_account_name_length
    MAX_ACCOUNT_NAME_LENGTH
  end

  def self.max_introduction_length
    MAX_INTRODUCTION_LENGTH
  end

  def self.guest
    guest_email = "guest_#{SecureRandom.hex(10)}@example.com"
    guest_account_name = "guest_#{SecureRandom.alphanumeric(12)}"

    create!(
      email: guest_email,
      account_name: guest_account_name,
      password: SecureRandom.urlsafe_base64,
      is_guest: true
    ) do |user|
      user.display_name = "ゲストユーザー"
      user.introduction = "ゲストユーザーです。"
      user.status = 0
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  # `RedirectHandler` モジュールのインクルード
  # このモジュールはリダイレクトに関する共通のメソッドを提供します。
  # 特定のアクション実行後、元のページに戻るための処理をサポートします。
  include RedirectHandler

  before_action :set_user, only: %i[show edit update]
  before_action :store_return_to, only: [:edit]

  def index
    @query = params[:query]
    @status = params[:status]
    @users = User.search(@query, @status).with_attached_profile_image.page(params[:page])
  end

  def show
    @user_artworks = @user.artworks.with_details.page(params[:page])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      default_path = admin_user_path(@user.account_name)
      notice = t("messages.user.profile.update_success")

      redirect_to determine_redirect_path(default_path), notice: notice
    else
      # `account_name` がバリデーションエラーで空になったときに
      # `ActionController::UrlGenerationError` が発生するため、
      # 明示的に `set_user` を呼び出してエラーを回避する
      set_user
      render :edit
    end
  end

  private
  def set_user
    @user = User.find_by(account_name: params[:account_name])
  end

  def user_params
    params.require(:user).permit(
      :display_name,
      :account_name,
      :introduction,
      :profile_image,
      :status
    )
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def user_status_options
    User.statuses.map { |key, _value| [t("enums.user.status.#{key}"), key] }
  end
end

app/views/admin/users/_details.html.erb
<div class="p-6 flex flex-col gap-4 lg:flex-row">
  <div class="flex justify-center items-center mx-16 shrink-0">
    <%= component "user/avatar", user: user, size: :xl %>
  </div>
  <div class="overflow-auto grow">
    <%= component "shared/table/base" do %>
      <%= component "shared/table/body" do %>
        <%= component(
          "shared/details_row",
          heading: t("activerecord.attributes.user.display_name")
        ) do %>
          <%= user.display_name %>
        <% end %>

        <%= component(
          "shared/details_row",
          heading: t("activerecord.attributes.user.account_name")
        ) do %>
          <%= user.account_name %>
        <% end %>

        <%= component(
          "shared/details_row",
          heading: t("activerecord.attributes.user.introduction")
        ) do %>
          <div class="whitespace-normal max-w-[32rem]">
            <%= user.introduction %>
          </div>
        <% end %>

        <%= component(
          "shared/details_row",
          heading: t("activerecord.attributes.user.status")
        ) do %>
          <%= component "user/status_label", status: user.status_before_type_cast, text: user.status_i18n %>
        <% end %>

        <%= component(
          "shared/details_row",
          heading: t("activerecord.attributes.user.created_at")
        ) do %>
          <%= tag.span l(user.created_at) %><%= tag.span "(#{created_at_in_words(user)})", class: "text-gray-500 ml-1" %>
        <% end %>

        <%= component(
          "shared/details_row",
          heading: t("activerecord.attributes.user.updated_at")
        ) do %>
          <% if same_time?(user.created_at, user.updated_at, ignore_milliseconds: true) %>
            <%= tag.span "-" %>
          <% else %>
            <%= tag.span l(user.updated_at) %><%= tag.span "(#{updated_at_in_words(user)})", class: "text-gray-500 ml-1" %>
          <% end %>
        <% end %>

      <% end %>
    <% end %>

    <div class="mt-10 flex justify-evenly">
      <%= component(
        "shared/button",
        style: :outline,
        color: :gray,
        path: admin_edit_user_path(user.account_name),
        class: "w-32"
      ) do %>
        <%= component "utils/icon_text", fa_class: "fa-solid fa-sliders" do %>
          <%= t("user.edit") %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/_search_form.html.erb
<div data-controller="accordion">
  <div class="px-6 py-4 flex justify-between items-center font-bold text-lg bg-gray-200">
    <div class="inline-block">
      <%= component("utils/icon_text", fa_class: "fa-solid fa-magnifying-glass") do %>
        <%= t("user.searches.heading") %>
      <% end %>
    </div>
    <button class="w-10 h-10 rounded-sm transition-colors hover:bg-gray-100" data-accordion-target="button" data-action="accordion#toggle">
      <i class="fa-solid fa-chevron-down transition-transform duration-500" data-accordion-target="chevron"></i>
    </button>
  </div>
  <div class="overflow-hidden transition-[height] duration-500" style="height: 0px;" data-accordion-target="content">
    <div class="mx-auto mt-6 mb-2 w-96" data-controller="admin-user-search">
      <%= component "user/admin/search/form", options: user_status_options %>
    </div>
  </div>
</div>

app/views/admin/users/_table.html.erb
<div class="overflow-auto">
  <%= component "shared/table/base" do %>
    <%= component "shared/table/header", headers: [
      "#",
      "",
      t("activerecord.attributes.user.display_name"),
      t("activerecord.attributes.user.account_name"),
      t("activerecord.attributes.user.introduction"),
      t("activerecord.attributes.user.status"),
      t("activerecord.attributes.user.created_at"),
      t("activerecord.attributes.user.updated_at"),
      ""
    ] %>
    <%= component "shared/table/body" do %>
      <%= render partial: "admin/users/table_row", collection: users, as: :user %>
    <% end %>
  <% end %>
</div>
<%= paginate users %>

app/views/admin/users/_table_row.html.erb
<%= component "shared/table/row" do %>
  <%= component "shared/table/cell", is_header: true do %>
    <%= user.id %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <div class="min-w-[32px]">
      <%= component "user/avatar", user: user, size: :xxs %>
    </div>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= link_to user.display_name, admin_user_path(user.account_name), class: "font-bold text-blue-500 hover:underline" %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= user.account_name %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= user.introduction %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= component "user/status_label", status: user.status_before_type_cast, text: user.status_i18n %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= tag.span created_at_in_words(user), class: "text-xs" %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= tag.span updated_at_in_words(user), class: "text-xs" %>
  <% end %>
  <%= component "shared/table/cell" do %>
    <%= component(
      "shared/button",
      style: :outline,
      color: :gray,
      path: admin_edit_user_path(user.account_name),
      class: "w-8 h-8 mx-auto my-0"
    ) do %>
      <i class="fa-solid fa-sliders"></i>
    <% end %>
  <% end %>
<% end %>

app/views/admin/users/edit.html.erb
<%= component "shared/card", class: "my-10 p-6" do %>
  <%= tag.h2 t("user.edit_heading") %>
  <div class="mt-6 mx-auto w-96">
    <%= form_with model: [:admin, @user], url: admin_update_user_path(@user.account_name), local: true do |f| %>
      <div class="grid gap-y-4">
        <div>
          <%= component "shared/form/label", form: f, field: :profile_image %>
          <div class="flex justify-center items-center">
            <%= component "user/avatar", user: @user, size: :xl %>
          </div>
        </div>

        <div>
          <%= component "shared/form/label", form: f, field: :display_name %>
          <%= component(
            "shared/form/text_field",
            form: f,
            field_type: :text_field,
            field_name: :display_name,
            size: :small,
            model: @user,
            placeholder: t("placeholder.display_name"),
            maxlength: User.max_display_name_length
          ) %>
        </div>

        <div>
          <%= component "shared/form/label", form: f, field: :account_name %>
          <%= component(
            "shared/form/text_field",
            form: f,
            field_type: :text_field,
            field_name: :account_name,
            size: :small,
            model: @user,
            placeholder: t("placeholder.account_name"),
            maxlength: User.max_account_name_length,
          ) %>
         </div>

        <div>
          <%= component "shared/form/label", form: f, field: :introduction %>
          <%= component(
            "shared/form/text_area",
            form: f,
            field_name: :introduction,
            rows: 3,
            model: @user,
            placeholder: t("placeholder.introduction"),
            maxlength: User.max_introduction_length
          ) %>
        </div>

        <div>
          <%= component "shared/form/label", form: f, field: :status %>
          <div class="flex items-center gap-4">
            <% User.statuses.keys.each do |status_key| %>
              <%= component(
                "shared/form/radio",
                form: f,
                field_name: :status,
                value: status_key,
                label_field: "status_#{status_key}",
                label_text: t("enums.user.status.#{status_key}"),
                checked: @user.status == status_key
              ) %>
            <% end %>
          </div>
        </div>

        <div class="mt-4 flex justify-center items-center">
          <%= component(
            "shared/button",
            style: :outline,
            color: :sky,
            type: :submit,
            class: "w-36 h-10"
          ) do %>
            <%= t("user.update") %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="mt-4 pt-4 border-t border-gray-300 space-y-1">
    <div>
      <%= component "shared/back_link", path: admin_user_path(@user.account_name), text: t("user.details") %>
    </div>
    <div>
      <%= component "shared/back_link", path: admin_users_path, text: t("user.list") %>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<%= component "shared/card", class: "my-10" do %>
  <%= render "admin/users/search_form" %>
<% end %>
<%= component "shared/card", class: "my-10" do %>
  <h2 class="ml-6"><%= t("user.list") %></h2>
  <div id="users" class="contents">
    <%= render "admin/users/table", users: @users %>
  </div>
<% end %>

app/views/admin/users/index.js.erb
{
  const usersTable = document.getElementById("users");
  if (usersTable) {
    usersTable.innerHTML = "<%= j(render "admin/users/table", users: @users) %>";
  }
}

app/views/admin/users/show.html.erb
<%= component "shared/card", class: "my-10 p-6" do %>
  <%= tag.h2 t("user.details") %>
  <div class="overflow-auto">
    <%= render "admin/users/details", user: @user %>
  </div>
  <div class="mt-4 pt-4 border-t border-gray-300 space-y-1">
    <div>
      <%= component "shared/back_link", path: admin_users_path, text: t("user.list") %>
    </div>
  </div>
<% end %>

<%= component "shared/card", class: "my-10" do %>
  <h2 class="ml-6"><%= t("artwork.list") %></h2>
  <%= render "admin/artworks/table", artworks: @user_artworks, show_author: false %>
<% end %>